Development
alonsofl/investment-conference pull request #1
Opened 2021-06-30 01:42 UTC by alonsofl

## Summary
Created a mobile-first conference website with HTML, CSS, and Javascript. With media queries for the desktop version.

### Details
- Navigation bar:
  - The navigation links get updated depending on the active URL.
  - Mobile version: The mobile menu opens over the page when the user clicks the hamburger menu and closes when the user clicks the "X" button, includes a call-to-action "But Ticket" button.
  - Desktop version: The desktop menu stays at the top of the page and shows the links in a row, includes a call-to-action "Buy Ticket" button
- Sections added to the homepage:
  - Header section, including conference name (with pattern), date, location, and buy ticket button.
  - Agenda section, including cards with images and descriptions and but ticket button.
    - Mobile version uses flexbox columns to align items.
    - Desktop version uses grid to align items in 3 columns.
  - Speakers section, including dynamically generated elements using javascript.
    - Mobile version uses flexbox columns to align items.
    - Desktop version uses grid to align items in 2 columns.
  - Buy Tickets section, including form styled with theme colors.
    - Borders.
    - Outlines.
  - Partners section, including demo-partners companies logos.
  - Footer, including Creative Commons logo and author Twitter username.
- Sections added to about:
  - Header section, including a box with call-to-action text box and contact email.
  - WHY section, including cards with hover effects.
    - Desktop version uses grid to align items in 3 columns.
  - Partners section (same as homepage).
  - Footer (same as homepage).
- Styles:
  - All buttons include hover, focus, and active states.
  - Header section changes depending on the active URL.

2021-06-30 03:17 UTC, smcommits requested changes
Hi @alonsofl, 

### You have done an excellent job. The project appears to be fantastic. It reflects great efforts and good understanding. The cloned page is almost identical to the original design. Excellent work!

### To make this project even better, there are some issues that you still need to work on. You are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


 ## Required Changes ♻️
_Please check the inline comments below._

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).__

2021-06-30 03:17 UTC, smcommits commented on styles/main.css
> +@import url("https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap");
- [ ] **You have used the same properties multiple times in your CSS. This violates the principle of DRY and makes it difficult to maintain the code. Please fix this**

You have used properties like `display: flex, list-style-none, text-align:center`, etc, multiple times in your code. You can extract these into classes. It will result in less code and better maintenance. Any property that does not require a relative value can be extracted in their own classes. It will be ideal and keep your code DRY.

2021-06-30 03:17 UTC, smcommits commented on styles/main.css
> +}
- [ ] **You have used a media query for the same size multiple times. Please fix this**

Using multiple media queries for the same size is not necessary. You can just use one media query for any size and all the code under it will be executed if the media matches.

2021-06-30 16:12 UTC, alonsofl commented on index.html
> +        <div class="list-item__desc-container">
Hi @smcommits! Thanks for your review and time :raised_hands: 

I would like to ask something about this recommendation because I get the point of using article tags for content that would actually make sense on its own. But the agenda cards aren't like blog entries, they talk about the points that will take place during the conference. Maybe it's because of the Lorem text, but I think the content wouldn't actually make sense without the rest of the conference page.

Please let me know what are your thoughts on this. I would really appreciate it :smiley:

2021-06-30 18:09 UTC, smcommits commented on index.html
> +        <div class="list-item__desc-container">
@alonsofl Yeah! You are right. In this case, I have missed that the point of agenda cards. Probably because of the lorem ipsum. If they are providing some details, you can `<ul>` tags. Generally, you want to use tags that give some meaning to your page.

2021-06-30 22:21 UTC, alonsofl commented on index.html
> +        <div class="list-item__desc-container">
@smcommits, thanks for your feedback! I added the `ul` to be more precise in the agenda section. And your recommendations about media queries at the end and using classes for repetitive CSS properties are really efficient :v: :man_technologist:

2021-06-30 22:41 UTC, Davidosky007 requested changes
Hi @alonsofl, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
* Please add a video presentation describing the project and its features in your readme 
* below are required changes please make the necessary changes  🙏 you are almost there 👍 
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-06-30 22:41 UTC, Davidosky007 commented on about.html
> +  <header class="header">
fixed 👍

2021-06-30 22:41 UTC, Davidosky007 commented on about.html
> +<!DOCTYPE html>
* Nice work adding the middle section design 👍 but it looks different from the original design please fix it.
# Your Design: 
![Screenshot (107)](https://user-images.githubusercontent.com/52497246/124039129-350c9300-d9fa-11eb-8cd0-d6aafe467e1b.png)

2021-06-30 22:41 UTC, Davidosky007 commented on index.html
> +    </section>
* Like the previous reviewer pointed this section is different from the original design.
# original: 
![Screenshot (110)](https://user-images.githubusercontent.com/52497246/124039932-c8929380-d9fb-11eb-90f0-8aee73f5be6a.png)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# yours : 
![Screenshot (109)](https://user-images.githubusercontent.com/52497246/124039969-dcd69080-d9fb-11eb-988d-011801e9f2c3.png)

2021-06-30 23:13 UTC, alonsofl commented on index.html
> +    </section>
Hello @Davidosky007! Thanks for your kind review.
I would like to ask about the last recommendation in the **Agenda Section** of my project. The last reviewer asked me to change the **background color**, not the content because in the guidelines for the capstone they say to use the same **layout, component, and spaces**, but not to re-do the same design. I am supposed to apply the layout using my topic. The Agenda section contains cards as well as the original design.
This also applies to your recommendation about the logo section that I added. The topics are different. A conference event doesn't have a competition like CC to choose a logo, the conference organizer is "dti" and I came up with another text to make it look original.

Please let me know your thought on this :raised_hands:

2021-06-30 23:35 UTC, Davidosky007 commented on index.html
> +    </section>
* @alonsofl  You can take this as a [OPTIONAL] suggestion as it wasn't pointed out by the previous reviewer 🙏

2021-07-01 00:17 UTC, MahmoudBakr23 approved these changes
Hi @alonsofl 😃, 

Great work and effort you made so far on this project and on the required changes from the previous reviewers. It looks great now. However, there is just a small **OPTIONAL** thing to do in the design which is the footer's logo image. It'd be better if it's the same logo and a little bigger 👍 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-01 00:23 UTC, alonsofl commented
Thanks for the review @MahmoudBakr23 ! :muscle:

2021-07-01 00:23 UTC, merged